spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
  datasource:
    hikari:
      maximum-pool-size: 5

mybatis:
  type-aliases-package: com.joo.jootopia.bean
  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://host:port/dbname
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

#if you want to change port
# server:
#   port: 9090